  spring:
    application:
      name: grabby-ai
    ai:
      openai:
        api-key: ${OPENAI_API_KEY}
        embedding:
          options:
            model: text-embedding-3-small
      anthropic:
        api-key: ${ANTHROPIC_API_KEY}
      ollama:
        base-url: http://localhost:11434
        chat:
          options:
            model: llama3
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB
    server:
      port: 8080
    springdoc:
      api-docs:
        path: /api-docs
    profiles:
      default: local
      active: ${SPRING_PROFILES_ACTIVE:${ENV:local}}
    mail:
      host: smtp.example.com
      port: 587
      username: ${MAIL_USERNAME:}
      password: ${MAIL_PASSWORD:}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  management:
    endpoints:
      web:
        exposure:
          include: health,info,prometheus
    endpoint:
      health:
        show-details: when_authorized
    metrics:
      tags:
        application: grabby-ai
        env: ${ENV:${spring.profiles.active:local}}
    tracing:
      sampling:
        probability: 1.0

        health:
          check:
            interval-ms: 300000   # 5분
            notify-on-success: false

        notification:
          email:
            enabled: false
            from: no-reply@example.com
            to: you@example.com
          kakao:
            enabled: true
            access-token: ${KAKAO_ACCESS_TOKEN:} # 사용자 액세스 토큰(talk_memo 스코프)
